name: Build & deploy to s3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      
      - name: Install dependencies
        run: npm i

      - name: Build app
        run: npm run build

      - name: Deploy
        run: aws s3 sync ./build s3://prueba-s3-react
